### ISSUE TITLE
Sendmail and friends?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-HPC/pilot-testing#10]
Just want to confirm that there's currently no way to use sendmail et al. for sending emails from a login node.

This is what I've tried on the login node:
```sh
$ echo "Subject: sendmail test" | sendmail -v my_masked_email@gmail.com
sendmail: fatal: parameter inet_interfaces: no local interface found for ::1
```
and
```sh
$ echo "Subject: sendmail test" | sendmail -v my_masked_email@gmail.com
sendmail: fatal: parameter inet_interfaces: no local interface found for ::1
```

I also checked whether it's possible to get email notifications from cron jobs using
```sh
MAILTO=my_masked_email@gmail.com
# */1 * * * * /usr/bin/date
```
but that appears to end up in the void(?).

**Comment by jlbl** [comment]
On Fri, 16 Jun 2017 at 2:41pm, Henrik Bengtsson wrote

> Just want to confirm that there's currently no way to use sendmail et 
> al. for sending emails from a login node.

As on the previous issue, the intent is to support this, but a lot of 
other tasks are in line first.

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Comment by HenrikBengtsson** [comment]
Migrated to wynton-ops-hub issue tracker.
