### ISSUE TITLE
Lmod (Lua Module System)

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-HPC/pilot-testing#11]
@jlbl, could you please install the [Lmod](https://lmod.readthedocs.io/) module system?

# Installation notes

The official installation notes can be found at https://lmod.readthedocs.io/en/latest/#installing-lmod, but are a bit convoluted and not clear about how to download Lmod.  I've written down a summary below that I've used over at Cancer Center.

## Requirements

* Lua - 5.1.4 already installed
* [Luarocks](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix) - I think this is available via `yum install luarocks` (*)

## Download Lmod
```sh
$ cd /tmp/$USER
$ wget https://github.com/TACC/Lmod/archive/7.6.tar.gz
$ tar -xvf 7.6.tar.gz
$ cd Lmod-7.6/
```

# Install Lmod
```sh
$ ./configure
$ sudo make pre-install
```

There are more advanced configuration settings concerning Lmod caches etc, but let's not worry about that for now.

---
(*) To install Luarocks from source, do:
```sh
$ cd /tmp/$USER
$ wget https://github.com/luarocks/luarocks/archive/v2.4.2.tar.gz
$ tar -xvf v2.4.2.tar.gz
$ cd luarocks-2.4.2/
```
and then
```sh
$ /configure
$ make build
$ sudo make install
```

**Comment by HenrikBengtsson** [comment]
Forgot to say: `make install` will add
```r
/etc/profile.d/z00_lmod.sh -> /opt/apps/lmod/lmod/init/profile
```
whereas `make pre-install` will not.  If you wanna stride carefully, you could start with the latter.  This will still allow me to test out the system installation (I've already have a working install under my account) without affecting any other users.

**Comment by jlbl** [comment]
On Tue, 1 Aug 2017 at 1:01pm, Henrik Bengtsson wrote

> @jlbl, could you please install the [Lmod](https://lmod.readthedocs.io/) 
> module system?

> ## Download Lmod
> ```sh
> $ cd /tmp/$USER
> $ wget https://github.com/TACC/Lmod/archive/7.6.tar.gz
> $ tar -xvf 7.6.tar.gz
> $ cd Lmod-7.6/
> ```
>
> # Install Lmod
> ```sh
> $ ./configure
> $ sudo make install
> ```

"./configure; make; make install" is about the last way I want to install 
something on the cluster.  Lmod-6.5.1 is available in EPEL (as is 
luarocks).  Is there any reason we can't use that version?  If so, are you 
up for packing 7.6 into an RPM?

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Comment by HenrikBengtsson** [comment]
I see. Please start with Lmod 6.5.1 then, and then I test what it provides / what is missing.

I could look into packing Lmod 7.6 in an RPM, but I have never ever done that, meaning it'll take some time.

BTW, and touched upon in https://github.com/UCSF-HPC/pilot-testing/issues/11#issuecomment-319494265, you may wanna disable the added `/etc/profile.d/z00_lmod.sh -> /opt/apps/lmod/lmod/init/profile` link for now, or at least if there are complaints about Lmod not working with certain Tcl-based modules (there are a few rather advanced corner cases that may break and need to be worked around).

**Comment by HenrikBengtsson** [comment]
@jlbl, if you could add these before the weekend, I could work on testing and documenting this over the weekend. (I understand if you've got better things to do)

**Comment by HenrikBengtsson** [comment]
I'm going to need a few days to test any Lmod installation and adjust the website information (https://ucsf-hpc.github.io/wynton/software/software-repositories.html).

@jjbl, when do you think you can get this in?

**Comment by jlbl** [comment]
On Wed, 9 Aug 2017 at 7:27am, Henrik Bengtsson wrote

> I'm going to need a few days to test any Lmod installation and adjust the website information (https://ucsf-hpc.github.io/wynton/software/software-repositories.html).
>
> @jjbl, when do you think you can get this in?

I've installed Lmod-6.5.1 from EPEL on qb3-login1 and all the nodes in the 
"old" test cluster.  AFAICT no one else is using modules on the test 
cluster, so I went ahead and let Lmod become the default module command.

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Comment by HenrikBengtsson** [comment]
Thanks, confirming:
```sh
$ module --version

Modules based on Lua: Version 6.5.1  2016-08-17 15:44
    by Robert McLay mclay@tacc.utexas.edu
```

For the record, browsing through the [ChangeLog](https://github.com/TACC/Lmod/blob/master/README.md), I don't see anything critical that I'm missing in Lmod 6.5.1 from my tests that this far has been using Lmod 7.4.  (There's one thing related to automatically generated content for the website, but I can handle that myself by loading my local installation of Lmod 7.x).

Closing - will reopen if any surprises show up.
