### ISSUE TITLE
Interactive compute node access?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-HPC/pilot-testing#7]
Is there a way to get interactive command-line access to compute nodes?  I'd like to be able to check and validate several software, run-time library needs etc. Submitting trial-and-error scripts via `qsub` is a bit tedious.  I've tried `qrsh` but get:
```sh
$ qrsh
Your "qrsh" request could not be scheduled, try again later.
```

**Comment by jlbl** [comment]
On Tue, 6 Jun 2017 at 8:22pm, Henrik Bengtsson wrote

> Is there a way to get interactive command-line access to compute nodes? 
> I'd like to be able to check and validate several software, run-time 
> library needs etc. Submitting trial-and-error scripts via `qsub` is a 
> bit tedious.  I've tried `qrsh` but get:
> ```sh
> $ qrsh
> Your "qrsh" request could not be scheduled, try again later.
> ```

Once the managment and queueing is in place, interactive nodes (read: 
nodes configured exactly as compute nodes but available via ssh) are on 
the todo list.

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF
