### ISSUE TITLE
Singularity 2.3 is available

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-HPC/pilot-testing#8]
Singularity 2.3 is now available and allows users to build / bootstrap container images without root privileges (so super awesome).  Cut'n'pastable installation instructions (same as previous versions) available at http://singularity.lbl.gov/install-linux.

Validation of 2.3 installation (as regular user - not root!):
```r
$ cd /tmp
$ singularity create r.img
$ singularity import r.img docker://rocker/r-base # some downloads
$ singularity exec r.img Rscript --version
R scripting front-end version 3.4.0 (2017-04-21)
```

The current version is:
```sh
$ singularity --version
2.2.1
```

**Comment by jlbl** [comment]
On Tue, 6 Jun 2017 at 8:37pm, Henrik Bengtsson wrote

> Singularity 2.3 is now available and allows users to build / bootstrap 
> container images without root privileges (so super awesome). 
> Cut'n'pastable installation instructions (same as previous versions) 
> available at http://singularity.lbl.gov/install-linux.

Singularity has been upgraded across the cluster.

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Comment by HenrikBengtsson** [comment]
Thanks. Confirming it works on interactive machine;
```sh
$ singularity create r.img
$ singularity import r.img docker://rocker/r-base # some downloads
$ singularity exec r.img Rscript --version
R scripting front-end version 3.4.0 (2017-04-21)
```

**Comment by HenrikBengtsson** [comment]
For the record, I've also confirmed it works on the compute nodes;

When submitting
```sh
$ qsub singularity.sge
```
with script:
```sh
[hb@qb3-login1 singularity]$ cat singularity.sge
#!/bin/env bash
#$ -S /bin/bash
#$ -l mem_free=1G       # Memory usage, required.  Note that this is per slot
#$ -l h_rt=00:00:02     # Run time, e.g. 2 minutes
#$ -pe smp 2            # Specify parallel environment and number of slots, required
#$ -R yes               # SGE host reservation, highly recommended
#$ -cwd                 # Current working directory
#$ -j y                 # Join STDERR and STDOUT
date
singularity exec r.img Rscript --version
```
I get:
```sh
$ [hb@qb3-login1 singularity]$ cat singularity.sge.o100227
Thu Jun  8 13:42:35 PDT 2017
R scripting front-end version 3.4.0 (2017-04-21)
```
Perfect.
