### ISSUE TITLE
Email notifications from jobs?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-HPC/pilot-testing#9]
Are SGE flags `-M` and `-m` supported, i.e. can users receive email notifications triggered by a job status update?

I've tried `qsub`:ing the below SGE script, which runs, but I don't receive any email notifications.

```sh
#!/bin/bash
#$ -S /bin/bash
#$ -l mem_free=1G       # Memory usage, required.  Note that this is per slot
#$ -l h_rt=00:00:02     # Run time, e.g. 2 minutes
#$ -pe smp 2            # Specify parallel environment and number of slots, required
#$ -R yes               # SGE host reservation, highly recommended
#$ -cwd                 # Current working directory
#$ -j y                 # Join STDERR and STDOUT
#$ -M my_masked_email@gmail.com
#$ -m beas

date
hostname
```

This is for the user docs / FAQs.

**Comment by jlbl** [comment]
On Fri, 16 Jun 2017 at 2:29pm, Henrik Bengtsson wrote

> Are SGE flags `-M` and ``-m` supported, i.e. can users receive email 
> notifications triggered by a job status update?

This is on the list to get configured, but fairly low on said list.

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Comment by HenrikBengtsson** [comment]
Moved to wynton-ops-hub tracker.
